### ISSUE TITLE
ModuleNotFoundError: No module named 'vgtk.cuda.grouping'

### ISSUE THREAD

**Issue by HIT-K** [UMich-CURLY/se3_equivariant_place_recognition#1]
hi
i use this command in linux to run Code:

CUDA_VISIBLE_DEVICES=0 python run_modelnet.py experiment -d /home/***/EvenAlignedModelNet40PC/

bet i have an error like this.
how can handle this error:

ModuleNotFoundError: No module named 'vgtk.cuda.grouping'

**Comment by chienerh** [comment]
Thank you for the interest in the work. This work did not test on ModelNet data set. However, if you have issues on finding the vgtk in the code, you could try the following steps:
1. Ensure you have built the vgtk package using the following command for EPN:
```
cd vgtk
python setup.py install
```
and the following command for E2PN:
```
git checkout e2pn
cd vgtk
python setup.py build_ext -i
```
2. To load the E2PN package, adding the following part of code on top of the file (before importing vgtk) would help it find the package:
```
# Local E2PN package
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__),'vgtk') )
```

Hope this helps!
